Mruiz/postcard modeland routes
gorillainsuit/cards-r-us pull request #26
Opened 2023-01-10 00:51 UTC by Ruizmichael

First draft

2023-01-11 02:58 UTC, Hidinkyu commented on backend/routes/cards.js
> +router.get('/', cardsController.createCard, (req, res) => {
This should be a post Req

2023-01-11 03:00 UTC, Hidinkyu requested changes
Only one small change.
In the backend/routes/cards.js
the create req should be router.post

2023-01-11 04:11 UTC, mjhult requested changes

2023-01-11 04:11 UTC, mjhult commented on backend/controllers/cardController.js
> +      const cards = await User.find({}).select('gallery');
Why query every user?

2023-01-11 04:11 UTC, mjhult commented on backend/controllers/cardController.js
> +    if (!mongoose.Types.ObjectId.isValid(id)) {
If receiving through params it will be of type string.

2023-01-11 04:11 UTC, mjhult commented on backend/controllers/cardController.js
> +    res.json({ message: 'Deleted card' });
It may be beneficial to return the deleted card id

2023-01-12 04:40 UTC, mjhult approved these changes

2023-01-13 01:14 UTC, closed without merging

2023-01-13 01:14 UTC, Ruizmichael commented
Redid this branch, will create new pull request.